FROM golang:1.13.10

ENV APPPATH $GOPATH/src/github.com/google/cloudprober

WORKDIR $APPPATH

RUN git clone -b v0.10.7 https://github.com/google/cloudprober.git  "$APPPATH" \
    && go get -d && GOBIN=$GOPATH/bin go install $GOPATH/src/github.com/google/cloudprober/cmd/cloudprober.go \
    && rm -rf "$GOPATH"

FROM prom/busybox:latest

# COPY ca-certificates.crt /etc/ssl/certs/ca-certificates.crt

ENTRYPOINT ["/cloudprober", "--logtostderr"]
