version: '3.8'
services:
  fluentd:
    image: ${DOCKER_HUB_USERNAME}/fluentd:${FLUENTD_VERSION}
    ports:
      - '24224:24224'
      - '24224:24224/udp'
    networks:
      - front_net
      - back_net

  elasticsearch:
    image: elasticsearch:7.6.2
    environment:
      - 'discovery.type=single-node'
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    expose:
      - 9200
    ports:
      - '9200:9200'
    networks:
      - front_net
      - back_net

  kibana:
    image: kibana:7.6.2
    ports:
      - '5601:5601'
    networks:
      - front_net
      - back_net

  zipkin:
    image: openzipkin/zipkin
    ports:
      - '9411:9411'
    networks:
      - front_net
      - back_net

volumes:
  elasticsearch_data:

networks:
  back_net:
  front_net:
