- hosts: all
  become: yes
  gather_facts: false
  tasks:
  - name: Install docker packages
    remote_user: immon4ik
    apt:
      name: "{{ item }}"
      state: present
      update_cache: yes
    with_items:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    tags:
      - docker-ms
  - name: Add Docker s official GPG key
    remote_user: immon4ik
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
    tags:
      - docker-ms
  - name: Verify that we have the key with the fingerprint
    remote_user: immon4ik
    apt_key:
      id: 0EBFCD88
      state: present
    tags:
      - docker-ms
  - name: Set up the stable repository
    remote_user: immon4ik
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
      state: present
      update_cache: yes
    tags:
      - docker-ms
  - name: Update apt packages
    remote_user: immon4ik
    apt:
      update_cache: yes
    tags:
      - docker-ms
  - name: Install docker
    remote_user: immon4ik
    apt:
      name: docker-ce
      state: present
      update_cache: yes
    tags:
      - docker-ms
  - name: Add remote "immon4ik" user to "docker" group
    remote_user: immon4ik
    user:
      name: "immon4ik"
      group: "docker"
      append: yes
    tags:
      - docker-ms
  - name: Install docker-compose
    remote_user: immon4ik
    get_url:
      url : https://github.com/docker/compose/releases/download/1.25.5/docker-compose-Linux-x86_64
      dest: /usr/local/bin/docker-compose
      group: docker
      mode: 'u+x,g+x,o+x'
    tags:
      - docker-ms
  - name: Install docker-machine
    remote_user: immon4ik
    get_url:
      url : https://github.com/docker/machine/releases/download/v0.16.2/docker-machine-Linux-x86_64
      dest: /usr/local/bin/docker-machine
      group: docker
      mode: 'u+x,g+x,o+x'
    tags:
      - docker-ms
