{
 "title": "Otus App",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1s",
 "templating": {
  "list": [
   { "name": "namespace", "label": "Environment:", "query": "label_values(namespace)" }
  ]
 },
 "panels": [
  {
   "title": "Robot - Number of pages parsed by Robot",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "crawler_pages_parsed{namespace=~\"$namespace\"}",
     "legendFormat": "Кол-во обработанных ботом страниц $namespace"
    }
   ]
  },
  {
   "title": "Robot - parsing time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(crawler_page_parse_time_bucket{namespace=~\"$namespace\"}[1m])) by (le))",
     "legendFormat": "Время затраченное ботом на обработку содержимого веб-страницы за минуту $namespace"
    }
   ]
  },
  {
   "title": "Robot - average time get pages",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(crawler_site_connection_time_bucket{namespace=~\"$namespace\"}[1m])) by (le))",
     "legendFormat": "Среднее время получения страницы $namespace"
    }
   ]
  },
  {
   "title": "Search Engine UI - requests count per min",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(web_pages_served{namespace=~\"$namespace\"}[1m])",
     "legendFormat": "Кол-во обработанных запросов за минуту $namespace"
    }
   ]
  },
  {
   "title": "Search Engine UI - average time page generate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(web_page_gen_time_bucket{namespace=~\"$namespace\"}[1m])) by (le))",
     "legendFormat": "Среднее время генерации страницы за минуту $namespace"
    }
   ]
  }
 ]
}