version: '3.8'
services:
  mongo_db:
    image: ${MONGO_DB_IMAGE}
    volumes:
      - ${MONGO_DB_VOL_NAME}:${MONGO_DB_VOL_DEST}
    networks:
        back_net:
            aliases:
                - ${MONGO_DB_BACK_NET_ALIAS}
        front_net:
            aliases:
                - ${MONGO_DB_FRONT_NET_ALIAS}
  rabbit_mq:
    depends_on:
      - mongo_db
    image: ${DOCKER_HUB_USERNAME}/${RABBIT_MQ_IMAGE}:${CI_COMMIT_TAG:-2.2.0}.${CI_COMMIT_SHORT_SHA:-0}
    volumes:
      - ${RABBIT_MQ_VOL_HOME_NAME}:${RABBIT_MQ_VOL_HOME_DEST}
      - ${RABBIT_MQ_VOL_CONFIG_NAME}:${RABBIT_MQ_VOL_CONFIG_DEST}
    ports:
      - ${RABBIT_MQ_PORT}:${RABBIT_MQ_PORT}/tcp
      - '8081:15672'
      - '5672:5672'
    networks:
      back_net:
        aliases:
          - ${RABBIT_MQ_BACK_NET_ALIAS}
  crawler:
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    depends_on:
      - rabbit_mq
    image: ${DOCKER_HUB_USERNAME}/${CRAWLER_IMAGE}:${CI_COMMIT_TAG:-2.2.0}.${CI_COMMIT_SHORT_SHA:-0}
    volumes:
      - ${CRAWLER_VOL_NAME}:${CRAWLER_VOL_DEST}
    networks:
      - ${NETWORK_BACK_NET}
    logging:
      driver: 'fluentd'
      options:
        fluentd-address: localhost:24224
        tag: service.crawler
  ui:
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    depends_on:
      - crawler
    image: ${DOCKER_HUB_USERNAME}/${UI_IMAGE}:${CI_COMMIT_TAG:-2.2.0}.${CI_COMMIT_SHORT_SHA:-0}
    volumes:
      - ${UI_VOL_NAME}:${UI_VOL_DEST}
    ports:
      - ${UI_PORT}:${UI_PORT}/tcp
    networks:
      - ${NETWORK_FRONT_NET}
    logging:
      driver: 'fluentd'
      options:
        fluentd-address: localhost:24224
        tag: service.ui
  fluentd:
    image: ${DOCKER_HUB_USERNAME}/fluentd:${CI_COMMIT_TAG:-2.2.0}.${CI_COMMIT_SHORT_SHA:-0}
    ports:
      - '24224:24224'
      - '24224:24224/udp'
    networks:
      - ${NETWORK_FRONT_NET}
      - ${NETWORK_BACK_NET}

volumes:
  db_crawler:
  mq_rabbit_home:
  mq_rabbit_config:
  bot_crawler:
  app_ui:

networks:
  back_net:
    driver: ${NETWORK_BACK_NET_DRIVER}
    ipam:
      driver: default
      config:
        - subnet: ${NETWORK_BACK_NET_SUBNET}
  front_net:
    driver: ${NETWORK_FRONT_NET_DRIVER}
    ipam:
      driver: default
      config:
        - subnet: ${NETWORK_FRONT_NET_SUBNET}
